// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckPasswordInfoRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	EncryptedPassword    string   `protobuf:"bytes,2,opt,name=encryptedPassword,proto3" json:"encryptedPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPasswordInfoRequest) Reset()         { *m = CheckPasswordInfoRequest{} }
func (m *CheckPasswordInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPasswordInfoRequest) ProtoMessage()    {}
func (*CheckPasswordInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CheckPasswordInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPasswordInfoRequest.Unmarshal(m, b)
}
func (m *CheckPasswordInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPasswordInfoRequest.Marshal(b, m, deterministic)
}
func (m *CheckPasswordInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPasswordInfoRequest.Merge(m, src)
}
func (m *CheckPasswordInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPasswordInfoRequest.Size(m)
}
func (m *CheckPasswordInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPasswordInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPasswordInfoRequest proto.InternalMessageInfo

func (m *CheckPasswordInfoRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CheckPasswordInfoRequest) GetEncryptedPassword() string {
	if m != nil {
		return m.EncryptedPassword
	}
	return ""
}

type CheckResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Pageinfo struct {
	Pn                   uint32   `protobuf:"varint,1,opt,name=Pn,proto3" json:"Pn,omitempty"`
	Psize                uint32   `protobuf:"varint,2,opt,name=Psize,proto3" json:"Psize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pageinfo) Reset()         { *m = Pageinfo{} }
func (m *Pageinfo) String() string { return proto.CompactTextString(m) }
func (*Pageinfo) ProtoMessage()    {}
func (*Pageinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Pageinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pageinfo.Unmarshal(m, b)
}
func (m *Pageinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pageinfo.Marshal(b, m, deterministic)
}
func (m *Pageinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pageinfo.Merge(m, src)
}
func (m *Pageinfo) XXX_Size() int {
	return xxx_messageInfo_Pageinfo.Size(m)
}
func (m *Pageinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Pageinfo.DiscardUnknown(m)
}

var xxx_messageInfo_Pageinfo proto.InternalMessageInfo

func (m *Pageinfo) GetPn() uint32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *Pageinfo) GetPsize() uint32 {
	if m != nil {
		return m.Psize
	}
	return 0
}

type IdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRequest) Reset()         { *m = MobileRequest{} }
func (m *MobileRequest) String() string { return proto.CompactTextString(m) }
func (*MobileRequest) ProtoMessage()    {}
func (*MobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *MobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRequest.Unmarshal(m, b)
}
func (m *MobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRequest.Marshal(b, m, deterministic)
}
func (m *MobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRequest.Merge(m, src)
}
func (m *MobileRequest) XXX_Size() int {
	return xxx_messageInfo_MobileRequest.Size(m)
}
func (m *MobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRequest proto.InternalMessageInfo

func (m *MobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type UpdateUserInfoRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday             uint64   `protobuf:"varint,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserInfoRequest) Reset()         { *m = UpdateUserInfoRequest{} }
func (m *UpdateUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoRequest) ProtoMessage()    {}
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UpdateUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoRequest.Unmarshal(m, b)
}
func (m *UpdateUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoRequest.Merge(m, src)
}
func (m *UpdateUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoRequest.Size(m)
}
func (m *UpdateUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoRequest proto.InternalMessageInfo

func (m *UpdateUserInfoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserInfoRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UpdateUserInfoRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UpdateUserInfoRequest) GetBirthday() uint64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

type UserInfoResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Birthday             uint32   `protobuf:"varint,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Role                 int32    `protobuf:"varint,7,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfoResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfoResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserInfoResponse) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfoResponse) GetBirthday() uint32 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *UserInfoResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInfoResponse) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

type CreateUserInfoRequest struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserInfoRequest) Reset()         { *m = CreateUserInfoRequest{} }
func (m *CreateUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserInfoRequest) ProtoMessage()    {}
func (*CreateUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *CreateUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserInfoRequest.Unmarshal(m, b)
}
func (m *CreateUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserInfoRequest.Merge(m, src)
}
func (m *CreateUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserInfoRequest.Size(m)
}
func (m *CreateUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserInfoRequest proto.InternalMessageInfo

func (m *CreateUserInfoRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CreateUserInfoRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserInfoRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type UserListResponse struct {
	Total                int32               `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*UserInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserListResponse) GetData() []*UserInfoResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CheckPasswordInfoRequest)(nil), "CheckPasswordInfoRequest")
	proto.RegisterType((*CheckResponse)(nil), "CheckResponse")
	proto.RegisterType((*Pageinfo)(nil), "Pageinfo")
	proto.RegisterType((*IdRequest)(nil), "IdRequest")
	proto.RegisterType((*MobileRequest)(nil), "MobileRequest")
	proto.RegisterType((*UpdateUserInfoRequest)(nil), "UpdateUserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "UserInfoResponse")
	proto.RegisterType((*CreateUserInfoRequest)(nil), "CreateUserInfoRequest")
	proto.RegisterType((*UserListResponse)(nil), "UserListResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0x8a, 0xfc, 0x35, 0xc1, 0x6e, 0xb3, 0x24, 0x46, 0x55, 0x2e, 0x46, 0x50, 0xea, 0xd2,
	0xb0, 0x29, 0x69, 0xa1, 0xd0, 0xf6, 0xe4, 0x50, 0x8a, 0xa1, 0x1f, 0x42, 0x90, 0x4b, 0x6f, 0xb2,
	0x76, 0xac, 0x88, 0xd8, 0x5a, 0x55, 0xbb, 0x26, 0xa8, 0x3f, 0xad, 0x3f, 0xa1, 0xbf, 0xaa, 0x68,
	0x57, 0x9f, 0xb6, 0x7a, 0xe8, 0xc9, 0x7e, 0xbb, 0x33, 0xf3, 0xe6, 0x3d, 0xcd, 0x0e, 0xc0, 0x5e,
	0x60, 0x4a, 0x93, 0x94, 0x4b, 0x6e, 0x5f, 0x86, 0x9c, 0x87, 0x5b, 0xbc, 0x56, 0x68, 0xbd, 0xdf,
	0x5c, 0xe3, 0x2e, 0x91, 0x99, 0xbe, 0x74, 0x18, 0x58, 0xb7, 0xf7, 0x18, 0x3c, 0xb8, 0xbe, 0x10,
	0x8f, 0x3c, 0x65, 0xab, 0x78, 0xc3, 0x3d, 0xfc, 0xb9, 0x47, 0x21, 0x89, 0x0d, 0xa3, 0xa4, 0x38,
	0xb6, 0x7a, 0xf3, 0xde, 0x62, 0xec, 0x55, 0x98, 0x5c, 0xc1, 0x19, 0xc6, 0x41, 0x9a, 0x25, 0x12,
	0x59, 0x99, 0x6b, 0x19, 0x2a, 0xe8, 0xf8, 0xc2, 0x79, 0x09, 0x13, 0xc5, 0xe2, 0xa1, 0x48, 0x78,
	0x2c, 0x90, 0x58, 0x30, 0x14, 0xfb, 0x20, 0x40, 0x21, 0x54, 0xe5, 0x91, 0x57, 0x42, 0xe7, 0x35,
	0x8c, 0x5c, 0x3f, 0xc4, 0x28, 0xde, 0x70, 0x32, 0x05, 0xc3, 0x8d, 0x55, 0xc0, 0xc4, 0x33, 0xdc,
	0x98, 0x9c, 0x43, 0xdf, 0x15, 0xd1, 0x2f, 0x54, 0x44, 0x13, 0x4f, 0x03, 0xe7, 0x12, 0xc6, 0x2b,
	0x56, 0xf6, 0x3c, 0x05, 0x23, 0xd2, 0xdd, 0xf6, 0x3d, 0x23, 0x62, 0xce, 0x0b, 0x98, 0x7c, 0xe5,
	0xeb, 0x68, 0x8b, 0x65, 0xc0, 0x0c, 0x06, 0x3b, 0x75, 0x50, 0x48, 0x2a, 0x90, 0xf3, 0x08, 0x17,
	0x77, 0x09, 0xf3, 0x25, 0xde, 0x09, 0x4c, 0x9b, 0x2e, 0x1c, 0x54, 0xcc, 0x5d, 0x89, 0xa3, 0xe0,
	0xe1, 0x9b, 0xbf, 0xc3, 0x42, 0x70, 0x85, 0xf3, 0xe2, 0x21, 0xc6, 0x0c, 0x53, 0xeb, 0x44, 0x17,
	0xd7, 0x28, 0xcf, 0x59, 0x47, 0xa9, 0xbc, 0x67, 0x7e, 0x66, 0x99, 0xf3, 0xde, 0xc2, 0xf4, 0x2a,
	0xec, 0xfc, 0xee, 0xc1, 0xd3, 0x9a, 0xb3, 0xf0, 0xa7, 0x83, 0x34, 0x69, 0xbb, 0x5c, 0x7f, 0x8a,
	0x5a, 0xd1, 0x49, 0x53, 0x51, 0xab, 0x51, 0xf3, 0xa0, 0xd1, 0x66, 0x43, 0x7d, 0x65, 0x66, 0x85,
	0x1b, 0x22, 0x06, 0x2d, 0x11, 0x04, 0xcc, 0x94, 0x6f, 0xd1, 0x1a, 0xaa, 0xae, 0xd4, 0x7f, 0x27,
	0x84, 0x8b, 0xdb, 0x14, 0x3b, 0x5c, 0x6b, 0x92, 0xf7, 0x8e, 0xc9, 0xff, 0x57, 0x8c, 0xf3, 0x5d,
	0x9b, 0xf4, 0x25, 0x12, 0xb2, 0x32, 0xe9, 0x1c, 0xfa, 0x92, 0x4b, 0x7f, 0x5b, 0xf8, 0xa4, 0x01,
	0x79, 0x0e, 0x26, 0xf3, 0xa5, 0x6f, 0x19, 0xf3, 0x93, 0xc5, 0xe9, 0xcd, 0x19, 0x3d, 0xf4, 0xd6,
	0x53, 0xd7, 0x37, 0x7f, 0x0c, 0x30, 0xf3, 0x2b, 0xf2, 0x0a, 0x4e, 0x3f, 0xa3, 0x2c, 0x8b, 0x93,
	0x31, 0x2d, 0xc7, 0xcf, 0xd6, 0xb9, 0x2d, 0xca, 0xb7, 0xf0, 0xa4, 0x08, 0x5e, 0x66, 0x7a, 0xae,
	0xc8, 0x94, 0xb6, 0x06, 0xcc, 0x3e, 0x66, 0x24, 0x57, 0x15, 0xc5, 0x32, 0x5b, 0x31, 0x02, 0xb4,
	0x9a, 0xd7, 0xae, 0xe8, 0x77, 0x00, 0xb5, 0xa7, 0x64, 0x46, 0x3b, 0x0d, 0xee, 0x4a, 0xfc, 0x08,
	0x50, 0x8f, 0x30, 0x99, 0xd1, 0xce, 0x79, 0xb6, 0x67, 0x54, 0xef, 0x03, 0x5a, 0xee, 0x03, 0xfa,
	0x29, 0xdf, 0x07, 0xe4, 0x7d, 0xf1, 0x46, 0xcb, 0x47, 0x4b, 0x9e, 0xd1, 0x7f, 0x6d, 0x06, 0x7b,
	0x4a, 0x5b, 0xcf, 0x79, 0x39, 0xfe, 0x31, 0xa4, 0x1f, 0x74, 0xbd, 0x81, 0xfa, 0x79, 0xf3, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x57, 0xc4, 0x1e, 0x82, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUserList(ctx context.Context, in *Pageinfo, opts ...grpc.CallOption) (*UserListResponse, error)
	GetUserByMobile(ctx context.Context, in *MobileRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	GetUserById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	CreateUser(ctx context.Context, in *CreateUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CheckPassword(ctx context.Context, in *CheckPasswordInfoRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserList(ctx context.Context, in *Pageinfo, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/User/GetUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserByMobile(ctx context.Context, in *MobileRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/User/GetUserByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/User/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/User/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/User/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CheckPassword(ctx context.Context, in *CheckPasswordInfoRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/User/CheckPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetUserList(context.Context, *Pageinfo) (*UserListResponse, error)
	GetUserByMobile(context.Context, *MobileRequest) (*UserInfoResponse, error)
	GetUserById(context.Context, *IdRequest) (*UserInfoResponse, error)
	CreateUser(context.Context, *CreateUserInfoRequest) (*UserInfoResponse, error)
	UpdateUser(context.Context, *UpdateUserInfoRequest) (*empty.Empty, error)
	CheckPassword(context.Context, *CheckPasswordInfoRequest) (*CheckResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetUserList(ctx context.Context, req *Pageinfo) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (*UnimplementedUserServer) GetUserByMobile(ctx context.Context, req *MobileRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByMobile not implemented")
}
func (*UnimplementedUserServer) GetUserById(ctx context.Context, req *IdRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedUserServer) CreateUser(ctx context.Context, req *CreateUserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServer) UpdateUser(ctx context.Context, req *UpdateUserInfoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServer) CheckPassword(ctx context.Context, req *CheckPasswordInfoRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPassword not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pageinfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User/GetUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserList(ctx, req.(*Pageinfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MobileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User/GetUserByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserByMobile(ctx, req.(*MobileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserById(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CheckPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPasswordInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CheckPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User/CheckPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CheckPassword(ctx, req.(*CheckPasswordInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserList",
			Handler:    _User_GetUserList_Handler,
		},
		{
			MethodName: "GetUserByMobile",
			Handler:    _User_GetUserByMobile_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _User_GetUserById_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "CheckPassword",
			Handler:    _User_CheckPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
